
import NodeElement from "./NodeElement"

let NodeElements: NodeElement[]
NodeElements = [
    {
        "ID": "M01",
        "Type": "Milestone",
        "Title": "Start",
        "Duration": 0 ,
        "PredecessorIDs": [],
        "FAZ": 2,
        "FEZ": undefined,
        "SAZ": undefined,
        "SEZ": undefined,
        "TotalBuffer":  undefined,
        "FreeBuffer": undefined,
    },
    {
        "ID": "M02",
        "Type": "Milestone",
        "Title": "Installation F",
        "Duration": 0 ,
        "PredecessorIDs": [],
        "FAZ": undefined,
        "FEZ": 10,
        "SAZ": undefined,
        "SEZ": 12,
        "TotalBuffer":  undefined,
        "FreeBuffer": undefined,
    },
    {
        "ID": "M03",
        "Type": "Milestone",
        "Title": "IBN Milestone 3",
        "Duration": 0 ,
        "PredecessorIDs": ["T05","T06"],
        "FAZ": undefined,
        "FEZ": undefined,
        "SAZ": undefined,
        "SEZ": 17,
        "TotalBuffer":  undefined,
        "FreeBuffer": undefined,
    },
    {
        "ID": "M04",
        "Type": "Milestone",
        "Title": "Customer Handover",
        "Duration": 0 ,
        "PredecessorIDs": ["T07"],
        "FAZ": undefined,
        "FEZ": undefined,
        "SAZ": undefined,
        "SEZ": 25,
        "TotalBuffer":  undefined,
        "FreeBuffer": undefined,
    },
    {
        "ID": "T01",
        "Type": "Test",
        "Title": "Test A",
        "Duration": 2 ,
        "PredecessorIDs": ["MS01"],
        "FAZ": undefined,
        "FEZ": undefined,
        "SAZ": undefined,
        "SEZ": undefined,
        "TotalBuffer":  undefined,
        "FreeBuffer": undefined,
    },
    {
        "ID": "T02",
        "Type": "Test",
        "Title": "Test B",
        "Duration": 4 ,
        "PredecessorIDs": ["T01"],
        "FAZ": undefined,
        "FEZ": undefined,
        "SAZ": undefined,
        "SEZ": undefined,
        "TotalBuffer":  undefined,
        "FreeBuffer": undefined,
    },
    {
        "ID": "T03",
        "Type": "Test",
        "Title": "Test C",
        "Duration": 3 ,
        "PredecessorIDs": ["T02"],
        "FAZ": undefined,
        "FEZ": undefined,
        "SAZ": undefined,
        "SEZ": undefined,
        "TotalBuffer":  undefined,
        "FreeBuffer": undefined,
    },
    {
        "ID": "T04",
        "Type": "Test",
        "Title": "Test D",
        "Duration": 2 ,
        "PredecessorIDs": ["T02"],
        "FAZ": undefined,
        "FEZ": undefined,
        "SAZ": undefined,
        "SEZ": undefined,
        "TotalBuffer":  undefined,
        "FreeBuffer": undefined,
    },
    {
        "ID": "T05",
        "Type": "Test",
        "Title": "Test E",
        "Duration": 1 ,
        "PredecessorIDs": ["T03","T04"],
        "FAZ": undefined,
        "FEZ": undefined,
        "SAZ": undefined,
        "SEZ": undefined,
        "TotalBuffer":  undefined,
        "FreeBuffer": undefined,
    },
    {
        "ID": "T06",
        "Type": "Test",
        "Title": "Test F",
        "Duration": 4 ,
        "PredecessorIDs": ["T03","MS2"],
        "FAZ": undefined,
        "FEZ": undefined,
        "SAZ": undefined,
        "SEZ": undefined,
        "TotalBuffer":  undefined,
        "FreeBuffer": undefined,
    },
    {
        "ID": "T07",
        "Type": "Test",
        "Title": "Test G",
        "Duration": 5 ,
        "PredecessorIDs": ["MS3"],
        "FAZ": undefined,
        "FEZ": undefined,
        "SAZ": undefined,
        "SEZ": undefined,
        "TotalBuffer":  undefined,
        "FreeBuffer": undefined,
    },
]

export default NodeElements